server:
  port: 8805
  servlet:
    context-path: /rabbitMq/publisher
spring:
  application:
    name: RabbitMqPublisher # 服务名称
  rabbitmq:
    host: ${ip} # IP
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: root
    password: 2762581@com
    listener:
      simple:
        prefetch: 1 # 每次从消息队列拿到消息的数量

logging:
  level:
    cn.itcast: info
    org.springframework: info