server:
  port: 8809
  servlet:
    context-path: /activemq/consumer
spring:
  application:
    name: ActiveMqConsumer # 服务名称
  activemq:
    broker-url: tcp://${ip}:61616
    user: root
    password: 2762581@com